include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    sort_constructors_first: false
    avoid_positional_boolean_parameters: false
    avoid_catches_without_on_clauses: false
    specify_nonobvious_property_types: false
    document_ignores: false
